// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt6NY-ONZF9oUZ8aYXYEtStonKNXWA5Fc',
    appId: '1:422152027618:web:d97a479b344a7ec6b5cdbb',
    messagingSenderId: '422152027618',
    projectId: 'crud-813bc',
    authDomain: 'crud-813bc.firebaseapp.com',
    storageBucket: 'crud-813bc.appspot.com',
    measurementId: 'G-1MZ852EHBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjWnjGrPteLnBGwh-btzd1b8D3uB-0aM',
    appId: '1:422152027618:android:40b67390097c47f1b5cdbb',
    messagingSenderId: '422152027618',
    projectId: 'crud-813bc',
    storageBucket: 'crud-813bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpVomz5qxNRyI-PSVl1U_gZLvd82BeNFo',
    appId: '1:422152027618:ios:873551b7b7e07067b5cdbb',
    messagingSenderId: '422152027618',
    projectId: 'crud-813bc',
    storageBucket: 'crud-813bc.appspot.com',
    iosBundleId: 'com.appskyloom.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpVomz5qxNRyI-PSVl1U_gZLvd82BeNFo',
    appId: '1:422152027618:ios:873551b7b7e07067b5cdbb',
    messagingSenderId: '422152027618',
    projectId: 'crud-813bc',
    storageBucket: 'crud-813bc.appspot.com',
    iosBundleId: 'com.appskyloom.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt6NY-ONZF9oUZ8aYXYEtStonKNXWA5Fc',
    appId: '1:422152027618:web:56800f8268adc6adb5cdbb',
    messagingSenderId: '422152027618',
    projectId: 'crud-813bc',
    authDomain: 'crud-813bc.firebaseapp.com',
    storageBucket: 'crud-813bc.appspot.com',
    measurementId: 'G-6FW85S3WE6',
  );
}
