// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUX3vwpa_v4qOaOLVecU5wBP4ZvK7mTbA',
    appId: '1:444702747457:web:a00d301483f1a3a1650fc0',
    messagingSenderId: '444702747457',
    projectId: 'auth-cf7a0',
    authDomain: 'auth-cf7a0.firebaseapp.com',
    storageBucket: 'auth-cf7a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASFHjehQfex66ToCvzIp0c86FQthzWHRM',
    appId: '1:444702747457:android:0f8ff50cedb059ef650fc0',
    messagingSenderId: '444702747457',
    projectId: 'auth-cf7a0',
    storageBucket: 'auth-cf7a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9hPNVJjiPhfFgu6QBbjdFbiIs6Tsxc8',
    appId: '1:444702747457:ios:c92d08a8c9df4e9d650fc0',
    messagingSenderId: '444702747457',
    projectId: 'auth-cf7a0',
    storageBucket: 'auth-cf7a0.appspot.com',
    iosBundleId: 'com.appskyloom.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm9hPNVJjiPhfFgu6QBbjdFbiIs6Tsxc8',
    appId: '1:444702747457:ios:c92d08a8c9df4e9d650fc0',
    messagingSenderId: '444702747457',
    projectId: 'auth-cf7a0',
    storageBucket: 'auth-cf7a0.appspot.com',
    iosBundleId: 'com.appskyloom.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUX3vwpa_v4qOaOLVecU5wBP4ZvK7mTbA',
    appId: '1:444702747457:web:e084c083eb958573650fc0',
    messagingSenderId: '444702747457',
    projectId: 'auth-cf7a0',
    authDomain: 'auth-cf7a0.firebaseapp.com',
    storageBucket: 'auth-cf7a0.appspot.com',
  );
}
