// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFakr74OFkz8qnAOeiIbRaEa7S9FxAQWI',
    appId: '1:1024492785632:web:506a54354a2b69b303e585',
    messagingSenderId: '1024492785632',
    projectId: 'myauth-5a8a1',
    authDomain: 'myauth-5a8a1.firebaseapp.com',
    storageBucket: 'myauth-5a8a1.appspot.com',
    measurementId: 'G-DPC7PRE4W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZZgHEXzb_a7uYApkPOnYAZQ6M8KGmko',
    appId: '1:1024492785632:android:9a0c7472a71ee00403e585',
    messagingSenderId: '1024492785632',
    projectId: 'myauth-5a8a1',
    storageBucket: 'myauth-5a8a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgcAdt7VEESh3mdDCwE4NDjxqODQ_Ue0',
    appId: '1:1024492785632:ios:bf5ea0cdd892e62303e585',
    messagingSenderId: '1024492785632',
    projectId: 'myauth-5a8a1',
    storageBucket: 'myauth-5a8a1.appspot.com',
    iosClientId:
        '1024492785632-go34ttmac526ghhe8u01kadl5d1450m1.apps.googleusercontent.com',
    iosBundleId: 'com.appskyloom.myauthtute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgcAdt7VEESh3mdDCwE4NDjxqODQ_Ue0',
    appId: '1:1024492785632:ios:bf5ea0cdd892e62303e585',
    messagingSenderId: '1024492785632',
    projectId: 'myauth-5a8a1',
    storageBucket: 'myauth-5a8a1.appspot.com',
    iosClientId:
        '1024492785632-go34ttmac526ghhe8u01kadl5d1450m1.apps.googleusercontent.com',
    iosBundleId: 'com.appskyloom.myauthtute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFakr74OFkz8qnAOeiIbRaEa7S9FxAQWI',
    appId: '1:1024492785632:web:8c8af426bcef762403e585',
    messagingSenderId: '1024492785632',
    projectId: 'myauth-5a8a1',
    authDomain: 'myauth-5a8a1.firebaseapp.com',
    storageBucket: 'myauth-5a8a1.appspot.com',
    measurementId: 'G-FDJ95NJF7W',
  );
}
